language: python
python:
  - 3.7
install:
  - python3 -m venv .
  - bin/pip install -r requirements.txt
script:
  - bin/pytest
after_success:
  - bin/coveralls

# deploy:
#   provider: pypi
#   user: "nens"
#   password:
#     secure: LongStringThatNeedsToBeSetByReinout
#   # (travis encrypt NENS-PASSWORD --com --add deploy.password)
#   on:
#     tags: true
#   distributions: "sdist bdist_wheel"
#   skip_existing: true
