language: python
python:
  - 3.7
install:
  - deactivate
  - /opt/python/3.7/bin/python -m venv .
  - bin/pip3 install -r requirements.txt
script:
  - bin/pytest
after_success:
  - bin/coveralls

# deploy:
#   provider: pypi
#   user: "nens"
#   password:
#     secure: LongStringThatNeedsToBeSetByReinout
#   # (travis encrypt NENS-PASSWORD --com --add deploy.password)
#   on:
#     tags: true
#   distributions: "sdist bdist_wheel"
#   skip_existing: true
